name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT }}
          export_default_credentials: true
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Create DotENV config
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_NEXT_PUBLIC_ANALYTICS_ID: ${{ secrets.INPUT_ENVKEY_GA_ID }}
          file_name: .env
      - name: Install Dependencies
        run: |
          npm install
          npm run build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --project already-won --only functions:nextjs-server,hosting:prod
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
